algoritmo "OperadoresRelacionais"

var
A, B, C: Inteiro

inicio
A <- 2
B <- 3
C <- 5

//====== Comparando variáveis ======
//escreva (A>B)
//escreva (A=B)
//escreva (A<>B)

//====== Comparando valores ======
//escreva (A>2)
//escreva (A>=2)

//====== Teste lógico com expressões ======
//escreva (C=A+B)
//escreva (C>=B^A)
//escreva (C<=B^A)
//escreva (B<=C%2)
escreva (1=C%2)



fimalgoritmo
